services:
  postgresql-db-user:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgresql-db-user:/var/lib/postgresql/data

  user-service:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql-db-user:5432/user_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - postgresql-db-user
    restart: on-failure

volumes:
  postgresql-db-user:
