spring.application.name=user_service

#spring.datasource.url=jdbc:postgresql://postgresql-db-user:5432/user_db
spring.datasource.url=jdbc:postgresql://localhost:5432/user_db?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

#accommodation.service.url=http://accommodation-service:8080
accommodation.service.url=http://localhost:8082
#reservation.service.url=http://reservation-service:8080
reservation.service.url=http://localhost:8083
#notification.service.url=http://notification-service:8080
notification.service.url=http://localhost:8085

server.port=8081
